### ISSUE TITLE
HTTP Example Missing Steps

### ISSUE THREAD

**Issue by stmcginnis** [zenoss/ZenPacks.zenoss.ZenPackLib#405]
The HTTP example appears to be missing something in modeler-plugin.rst. When describing the modpath value it states: "we defined the WundergroundLocation class in __init__.py".

There was nowhere in this or previous example steps that added a class to __init__.py. Following the tutorial up to this point does not result in a working ZenPack. If I continue on and try to deploy it I get the message "No Python plugins found" when trying to run zendisc at the end of the instructions in add-device-class.

**Comment by cluther** [comment]
@stmcginnis: Thanks for the report. It looks like the HTTP API tutorial has some dated information from before it used zenpacklib, and definitely before zenpacklib v2. I'll make a sweep through there and get it up to date.

In this particular case the WundergroundLocation class it's referring to is just what you defined in zenpack.yaml's classes section.

**Comment by cluther** [comment]
@stmcginnis: I ran through the HTTP API tutorial and corrected a few things that needed updated for the latest versions of everything (f4a2529). Though I didn't find anything that I think would lead to a "No Python plugins found" after completing the _Create a Modeler Plugin_ section.

The most common cause of "No Python plugins found" I've seen is zenhub being unable to import the Locations class module due to some syntax error. A good way to troubleshoot this is to run _zendmd_, and attempt to import the class as follows.

```python
from ZenPacks.training.WeatherUnderground.modeler.plugins.WeatherUnderground.Locations import Locations
```

You'll need to fix any errors that appear as a result of this import. Once it imports with no errors, you should be sure to restart the _zenhub_ service with `serviced service restart zenhub`, then attempt to model the device again.

If you still see the "No Python plugins found" log, then maybe it's just that the WeatherUnderground.Locations modeler plugin isn't configured for the device. Check _Modeler Plugins_ for the /WeatherUnderground device class, and be sure that it includes the WeatherUnderground.Locations modeler plugin. Then just to be sure, check the specific device's modeler plugins to be sure that isn't overriding the /WeatherUnderground device class to exclude that modeler plugin.

**Comment by stmcginnis** [comment]
Thanks @cluther! I did indeed have a copy/paste error in my Locations.py code. And thanks for clearing up the docs.

Do you have a ZenPack on github that you could point me to using the latest zenpacklib? Most examples I can find, even with ones using zenpack.yaml, appear to have an odd mix of old and new styles that is making it a little confusing trying to figure some things out.

And sorry to hijack this issue for off topic questions. If there is a better forum (mailing list?) for ZenPack development questions, just let me know the preferred way. Thanks!

**Comment by j053ph4** [comment]
Hi,

I recently created a repository:

https://github.com/zenoss/ZenPacks.zenoss.ZenPackLibDemo

That is intended to demonstrate ZenPackLib and to give examples of how to perform common development tasks.  It's still pretty basic at the moment, but I intend to add more examples to it and hope that it will become a good source for "best practices" and things like that.  I'm pretty sure it's publicly accessible, but let me know if you can't view it for some reason.

Joseph Anderson

**Comment by stmcginnis** [comment]
Thanks @j053ph4 - I can get to the repo and on first glance, it sounds like it should be a good resource. Thanks!
